name: CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

  workflow_dispatch:

jobs:
  deploy:
    name: Job 1 - GitHub hosted
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Incrementar versión
        run: |
          echo "AppVersion-2 - $(date '+%Y-%m-%d %H:%M:%S')" >> README.md

      - name: Guardar cambios
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add README.md
          git diff --cached --quiet || git commit -m "Incrementar versión [skip ci]"

          if [ "${{ github.event_name }}" = "pull_request" ]; then
            git fetch origin "${{ github.head_ref }}"
            git pull --rebase origin "${{ github.head_ref }}"
            git push origin HEAD:"${{ github.head_ref }}"
          else
            git pull --rebase origin main
            git push
          fi
  validate:
    name: Job 2 - Self hosted
    runs-on: self-hosted
    needs: deploy

    steps:
      - name: Validar PROD_TOKEN
        env:
          PROD_TOKEN: ${{ secrets.PROD_TOKEN }}
        run: |
          if [ -z "$PROD_TOKEN" ]; then
            echo "PROD_TOKEN no está configurado"
            exit 1
          fi

          echo "PROD_TOKEN está configurado correctamente"
