name: CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

  workflow_dispatch:

jobs:
  deploy:
    name: Job 1 - GitHub hosted
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Incrementar versión
        run: |
          echo "AppVersion-2 - $(date '+%Y-%m-%d %H:%M:%S')" >> README.md

      - name: Guardar cambios
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add README.md

          if git diff --cached --quiet; then
            echo "No hay cambios que guardar"
            exit 0
          fi

          git commit -m "Incrementar versión [skip ci]"
  
          if [ "${{ github.event_name }}" = "pull_request" ]; then
             git pull --rebase origin "${{ github.head_ref }}"
             git push origin HEAD:"${{ github.head_ref }}"
          else
             git pull --rebase origin main
             git push origin HEAD:main
          fi
  validate:
   name: Job 2 - Self hosted
    runs-on: self-hosted
    needs: deploy

    steps:
      - name: Validar PROD_TOKEN
        shell: powershell
        env:
          PROD_TOKEN: ${{ secrets.PROD_TOKEN }}
        run: |
          if ([string]::IsNullOrEmpty($env:PROD_TOKEN)) {
            Write-Error "Falta PROD_TOKEN"
            exit 1
          }
          Write-Host "PROD_TOKEN configurado correctamente"
