name: Job 2 - Self hosted
    runs-on: self-hosted
    needs: deploy

    steps:
      - name: Validar PROD_TOKEN
        shell: powershell
        env:
          PROD_TOKEN: ${{ secrets.PROD_TOKEN }}
        run: |
          if ([string]::IsNullOrEmpty($env:PROD_TOKEN)) {
            Write-Error "Falta PROD_TOKEN"
            exit 1
          }
          Write-Host "PROD_TOKEN configurado correctamente"
